<h2>Welcome to CherryPHP</h2>

<div style="overflow:none; width:900px;">
<div style="float:left; width:300px;">
    <h3>What is this thing?</h3>
    <p>This is the MVC template website for CherryPHP.</p>
</div>
<div style="float:left; width:550px;">

<h3>Extensions</h3>
<p>Extensions are easily embedded into any part of your application or website. By using <code>&lt;@uuid /&gt;</code> you can for example
    embedd an UUID, assuming the uuidextension is loaded.</p>
<p>This will automatically load any dependencies, such as the <code>cherry.crypto</code> bundle which has the classes for UUID generation.</p>
<blockquote><p>Here is an UUID for you: <code><@uuid version="4"></code></p></blockquote>

<h3>Bundles</h3>
<p>This application is built on top of the <code>cherry.mvc</code> bundle. It is automatically loaded by the bootstrap.</p>

</div>
</div>
