<div id="wrap">
    <div class="container">
        <div class="col w-full header-container">
            <div class="header-text">CherryTree: A Light and Extensible CMS</div>
        </div>
    </div>
    <div class="container navigation-container">
        <div class="col w-8 navigation">
            <ul class="navigation">
                <li><a href="/">Home</a></li>
                <li><a href="/about">About CherryTree</a></li>
            </ul>
        </div>
        <div class="col w-1"></div>
        <div class="col w-3" style="height:28px; line-height:28px;">Search</div>
    </div>
    <div class="container">
        <div class="col sub w-9">
            <div class="col w-3">
                <img src="/images/box-1.jpg">
                <h2>Lightweight</h2>
            </div>
            <div class="col w-3">
                <img src="/images/box-2.jpg">
                <h2>Free</h2>
                <em>CherryTree</em> is Open Source. The same goes for the
                framework powering it, <em>Cherry</em>.
            </div>
            <div class="col w-3">
                <img src="/images/box-3.jpg">
                <h2>Modern</h2>
                <em>CherryTree</em> has been written to use all the goodness
                that is HTML5 and CSS3. This includes CSS animations, form
                validation and a lot of other awesome features.
            </div>
        </div>
        <div class="col w-3"><@include type="widget" class="CherryTree.Widgets.Sidebar" scope="none"></div>
    </div>
    <div class="container">
        <div class="col w-2">Foot</div>
        <div class="col w-2">Foot</div>
        <div class="col w-2">Foot</div>
        <div class="col w-2">Foot</div>
        <div class="col w-4">
            Powered by CherryTree
        </div>
    </div>
</div>

<div id="controls">
    <div id="panels">
        <div class="group">
            <div class="header">Current Page</div>
            <div class="content">
                <label for="-meta-pagename">Page name (title)</label>
                <div><input type="text"></div>
                <a href="#" onclick="$('overlay').addClassName('visible');">Overlays!</a>
            </div>
        </div>
    </div>
    <div id="paneltabs">
        <a class="current" href="#"><img src="/images/fugue/layout-3.png"></a>
        <a href="#"><img src="/images/fugue/images.png"></a>
        <a href="#">X</a>
        <a href="#">X</a>
    </div>
</div>
<div id="overlay" class="non-visible"></div>
<div class="dialog" style="display:none;">Create new page</div>
