<!DOCTYPE HTML>
<html lang="en-us">
<head>
    
</head>
<body>
    <div id="header">
        
    </div>
    <ul id="navigation">
    <? foreach((array)$this->menuitems as $menuitem): ?>
        <li style="background-image:url(<?=$menuitem->icon?>)"><a href="<?=$menuitem->url?>"><?=$menuitem->label?></a></li>
    <? endforeach; ?>
    </ul>
    <div id="content"><@content /></div>
    
</body>
</html>