#!/usr/bin/php
<?php

/*
//LOADER:BEGIN
require('cherryphp.php');
App::bootstrap(__FILE__);
//LOADER:END
*/

//LOADER:BEGIN
if (!( @include_once "lib/bootstrap.php" )) {
    $libpath = getenv('CHERRY_LIB');
    if (!$libpath) {
        fprintf(STDERR,"Define the CHERRY_LIB envvar first.");
        exit(1);
    }
    require_once($libpath.'/lib/bootstrap.php');
}
//LOADER:END

$lepton = new \cherry\Lepton(__FILE__);

use cherry\base\Event;
use cherry\base\EventEmitter;
use cherry\BundleManager;
use Cherry\Extension\ExtensionManager;
use Cherry\Cache\CacheObject;


//BundleManager::load('cherry.net');

//\Cherry\debug('Attempting to access cache object...');
//\Cherry\Cache::get('foo');


function doimage($var) {
    return [ "imagedata:".$var->color, "image/jpeg", "30m" ];
}

// Shorthand method to output or cache an object via callback:
// (new CacheObject('images/logo.png', CacheObject::CO_DELAY | CacheObject::CO_USE_DISK,'doimage',[ 'color'=>'red' ]))->output();

// More hands-on approach to output or cache an object via callback:
// $co = new CacheObject('images/logo.png', CacheObject::CO_DELAY | CacheObject::CO_USE_DISK,'doimage',[ 'color'=>'blue' ]);
// echo $co->getContent()."\n";
// echo $co->getContentType()."\n";

/*
use Cherry\Cache\Cache;
$ci = Cache::getInstance();
echo "Set: ".$ci->set('foo','bar')."\n";
echo "Get: ".$ci->get('foo')."\n";

$mc = \Cherry\Cache\Memcached::getInstance();
echo "Set: ".$mc->updateValue('foo','bar')."\n";
echo "Get: ".$mc->getValue('foo')."\n";

// Fetch an URL
App::context()->url = 'http://www.google.com';
$doc = CacheObject::getUrl(App::context()->url);
echo "Got ".strlen($doc)." bytes of data!\n";
die();
*/

list($tot,$single) = \Cherry\Base\Diag::benchmark(1000,function() {
    $doc = CacheObject::getUrl('http://www.google.com',true);
});
printf("5 hits against url, %fs (%fs)\n", $tot, $single);

list($tot,$single) = \Cherry\Base\Diag::benchmark(1000,function() {
    $doc = CacheObject::getUrl('http://www.google.com');
});
printf("50 hits against cache, %fs (%fs)\n", $tot, $single);

list($tot,$single) = \Cherry\Base\Diag::benchmark(1000,function() {
    $doc = CacheObject::getUrl(__FILE__,true);
});
printf("5 hits against file, %fs (%fs)\n", $tot, $single);

list($tot,$single) = \Cherry\Base\Diag::benchmark(1000,function() {
    $doc = CacheObject::getUrl(__FILE__);
});
printf("50 hits against file cache, %fs (%fs)\n", $tot, $single);

/*
// This is how the caching will mostly be used
$html = new CacheObject(
            'navigation.html',
            CacheObject::CO_DELAY | CacheObject::CO_USE_DISK | CacheObject::CO_COMPRESS
);
if (!$html->output()): $html->bufferContent(); ?>
<html><head><title>Foo</title></head>
<body>Hello World</body></html>
<? $html->bufferEnd(); endif; ?>
<? $ct = $html->getContentType(); echo "\nType: {$ct}\n"
*/
