#!/usr/bin/php
<?php

//LOADER:BEGIN
if (!( @include_once "lib/bootstrap.php" )) {
    $libpath = getenv('CHERRY_LIB');
    if (!$libpath) {
        fprintf(STDERR,"Define the CHERRY_LIB envvar first.");
        exit(1);
    }
    require_once($libpath.'/lib/bootstrap.php');
}
//LOADER:END

$lepton = new \cherry\Lepton(__FILE__);

use cherry\base\Event;
use cherry\base\EventEmitter;
use cherry\BundleManager;
use Cherry\Extension\ExtensionManager;

$bm = BundleManager::getInstance();
$bm->load('cherry.crypto');

// Example: Crypto
$str = 'Hello World';
$key = 'FooBar';

$enc = \Cherry\Crypto\Algorithm::tripledes($key)->encrypt($str);
$dec = \Cherry\Crypto\Algorithm::tripledes($key)->decrypt($enc);

// Example: Crypto (#2)
$str = 'Hello World';
$key = 'FooBar';

$ca = new \Cherry\Crypto\Algorithm('tripledes',$key);
$enc = $ca->encrypt($str);

// Example. GnuPG

$kr = new \Cherry\Crypto\GnuPG\KeyRing();
$keys = $kr->getKeys();

foreach($keys as $key) {
    printf("%s (%s)\n", $key->uids[0]->name, $key->uids[0]->email);
}
