#!/usr/bin/php
<?php

//LOADER:BEGIN
if (!( @include_once "lib/bootstrap.php" )) {
    $libpath = getenv('CHERRY_LIB');
    if (!$libpath) {
        fprintf(STDERR,"Define the CHERRY_LIB envvar first.");
        exit(1);
    }
    require_once($libpath.'/lib/bootstrap.php');
}
//LOADER:END

\Cherry\BundleManager::load('cherry.cwt');

use Cherry\Cwt\Application;
use Cherry\Cwt\Dialog;
use Cherry\Cwt\DialogAction;
use Cherry\Cwt\Widgets\Label;
use Cherry\Cwt\Widgets\ButtonBar;
use Cherry\Cwt\Widgets\MenuBar;
use Cherry\Cwt\Widgets\Menu;
use Cherry\Cwt\Widgets\MenuItem;
use Cherry\Cwt\Widgets\Statusbar;

class DlgWelcome extends Dialog {
    function __construct() {

        parent::__construct();

        $this->title = "Welcome to CWT";

        $this->dialog->push('welcometext', new Label());
        $this->dialog->welcometext->label =
            "\n".
            "Welcome to Cherry Widget Toolkit!\n".
            "\n";
        $this->dialog->push('buttonbar', new ButtonBar());
        $this->dialog->buttonbar->addButton('ok','Ok',array($this,'close'));

    }
}

class CwtApplication {

    private $cwt = null;

    function __construct() {

        $this->cwt = new \Cherry\Cwt\Cwt();

    }

    function initMenus($desk) {

        $desk->menubar = new MenuBar();
        $file = new Menu();
        $file->addItem(new MenuItem('mnuFileNew','_New...',null,'c-N'));
        $file->addItem(new MenuItem('mnuFileSave','_Save',MenuItem::MENU_DISABLED,'c-S'));
        $file->addItem(new MenuItem('mnuFileSaveas','Save _as...',null,'m-F9'));
        $file->addSeparator();
        $file->addItem(new MenuItem('mnuFileQuit','_Quit',null,'c-Q'));

        $desk->menubar->addMenu('mnuFile','_File',$file);

    }

    function initUi() {

        //$cwt = new \Cherry\Cwt\Cwt();
        // $cwt->on(\Cherry\Cwt\Cwt::EVT_SIGINT, function(){ });
        $desk = new \Cherry\Cwt\Layouts\VerticalStack(array(
            'menubar' => 1,
            'body' => -1,
            'statusbar' => 1
        ));

        $this->cwt->setDesktop($desk);

        $desk->statusbar = new StatusBar();
        $this->initMenus($desk);

        $desk->menubar->on(MenuBar::EVT_CLICK,function(Cwt $cwt,MenuItem $menuitem){
            switch($menuitem->name) {
                case 'mnuFileNew':
                    $cwt->showModal(new DlgNew());
                    break;
                case 'mnuFileSaveas':
                    $dlg = new SaveDialog();
                    $cwt->showModal($dlg);
                    break;
                case 'mnuFileQuit':
                    $cwt->showModal();
                    break;
            }
        });

    }

    function main() {

        $this->initUi();
        /*
        $cwt->push('desktop',$desk);
        $cwt->on(Cwt::EVT_START,function(Cwt $cwt){
            $cwt->showModal(new DlgWelcome());
        });
        $cwt->run();

        */

        \cherry\debug('Cleaning up...');

    }

}

$app = new CwtApplication();
$app->main();
