#!/usr/bin/php
<?php

//LOADER:BEGIN
if (!( @include_once "lib/bootstrap.php" )) {
    $libpath = getenv('CHERRY_LIB');
    if (!$libpath) {
        fprintf(STDERR,"Define the CHERRY_LIB envvar first.");
        exit(1);
    }
    require_once($libpath.'/lib/bootstrap.php');
}
//LOADER:END

$lepton = new \cherry\Lepton(__FILE__);

use cherry\base\Event;
use cherry\base\EventEmitter;
use cherry\BundleManager;
use Cherry\Extension\ExtensionManager;

$bm = BundleManager::getInstance();
$bm->load('cherry.net');
$bm->load('cherry.crypto');

\Cherry\debug('Will grab consoleadapter, and then fail gloriuosly!');

$ca = \Cherry\Cli\Console::getAdapter();
$ca->write("Console acquired: %s\n",get_class($ca));

$foo = 'hello';
\assert($foo != 'hello');
\user_error("Oh Glorious Fail!");
