#!/usr/bin/php
<?php

//LOADER:BEGIN
if (!( @include_once "lib/bootstrap.php" )) {
    $libpath = getenv('CHERRY_LIB');
    if (!$libpath) {
        fprintf(STDERR,"Define the CHERRY_LIB envvar first.");
        exit(1);
    }
    require_once($libpath.'/lib/bootstrap.php');
}
//LOADER:END

$lepton = new \cherry\Lepton(__FILE__);

use Cherry\Net\SocketServer;
use Cherry\Net\Socket;
use Cherry\Net\SocketClient;
use Cherry\Net\Socket\Transport\TcpTransport;
use Cherry\Net\Socket\Transport\TlsTransport;


$ss = new SocketServer(6667);
$ss->on('connection', function($socket) {
    $sock = new Socket($socket);
    $sock->setTransport(new TcpTransport());
    $sock->setEndpoint(new GameSession());
    return $sock;
});
$ss->on('ready', function() {
    printf("Server is ready.\n");
});
$ss->start();

class GameSession extends SocketEndpoint {
    public function __construct() {
        $this->addTimer(1000,[$this,'timer']);
    }
    public function timer() {
        // Do something
    }
    public function onSocketAccept() { }
    public function onSocketClose() { }
    public function onSocketReceive($data) {
        $this->upgradeTransport(new TlsTransport());
    }
    public function onSocketUpgrade() { }
}
